"""empty message

Revision ID: 8c45f1d4a4c8
Revises: c49697d91f4d
Create Date: 2024-01-30 18:39:11.881862

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8c45f1d4a4c8'
down_revision = 'c49697d91f4d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('first_name', sa.String(length=120), nullable=False))
        batch_op.add_column(sa.Column('second_name', sa.String(length=120), nullable=False))
        batch_op.add_column(sa.Column('user_name', sa.String(length=120), nullable=False))
        batch_op.add_column(sa.Column('age_user', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('country_user', sa.String(length=120), nullable=False))
        batch_op.drop_column('is_active')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=False))
        batch_op.drop_column('country_user')
        batch_op.drop_column('age_user')
        batch_op.drop_column('user_name')
        batch_op.drop_column('second_name')
        batch_op.drop_column('first_name')

    # ### end Alembic commands ###
